### ISSUE TITLE
Logo do Software Público Brasileiro

### ISSUE THREAD

**Issue by uira** [dadosgovbr/kit#19]
![image](https://user-images.githubusercontent.com/89998/57961286-4b236c00-78e4-11e9-80e7-da63f3e69686.png)

**Comment by augusto-herrmann** [comment]
Olá, @uira !

Não entendi. Tem alguma referência ao SPB no Kit para Dados Abertos que precisaria ser atualizada? Procurei e não encontrei.

**Comment by uira** [comment]
Duh! Era um sandbox, @augusto-herrmann, mas só agora vi que usei o repositório errado. #desculpaê
